# Generated by Django 4.2.6 on 2023-10-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesatest', '0002_transactioncallback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business2Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OriginatorConversationID', models.CharField(max_length=255)),
                ('ConversationID', models.CharField(max_length=255)),
                ('ResponseCode', models.CharField(max_length=10)),
                ('ResponseDescription', models.CharField(max_length=255)),
            ],
        ),
    ]
